apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
  namespace: argo-system
spec:
  description: Application workloads
  sourceRepos:
    - 'https://github.com/blackjokie/k8s-manifest'
  destinations:
    # - namespace: 'app-*'
    #   server: https://kubernetes.default.svc
    - namespace: 'development-*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'networking.k8s.io'
      kind: IngressClass   # ✅ IZINKAN IngressClass

  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
    - group: 'rbac.authorization.k8s.io'
      kind: Role
    - group: 'rbac.authorization.k8s.io'
      kind: RoleBinding

  roles:
    - name: developer
      description: Developer access
      policies:
        - p, proj:development:developer, applications, get, applications/*, allow
        - p, proj:development:developer, applications, sync, applications/*, allow
      groups:
        - team-development
