apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production
  namespace: argocd-system
spec:
  description: Application workloads
  sourceRepos:
    - 'https://github.com/blackjokie/k8s-manifests'
  destinations:
    # - namespace: 'app-*'
    #   server: https://kubernetes.default.svc
    - namespace: 'default'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
  roles:
    - name: developer
      description: Developer access
      policies:
        - p, proj:production:developer, applications, get, applications/*, allow
        - p, proj:production:developer, applications, sync, applications/*, allow
      groups:
        - team-production
        