apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging
  namespace: argo-system
spec:
  description: Application workloads
  sourceRepos:
    - 'https://github.com/blackjokie/k8s-manifest'
  destinations:
    # - namespace: 'app-*'
    #   server: https://kubernetes.default.svc
    - namespace: 'staging-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
  roles:
    - name: developer
      description: Developer access
      policies:
        - p, proj:staging:developer, applications, get, applications/*, allow
        - p, proj:staging:developer, applications, sync, applications/*, allow
      groups:
        - team-staging
        