apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-guestbook
  namespace: argo-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    repoURL: https://github.com/blackjokie/k8s-manifests
    targetRevision: HEAD
    path: apps/staging/staging-guestbook
    directory:
      recurse: true  # penting: ini agar semua subfolder dibaca
  destination:
    server: https://kubernetes.default.svc
    namespace: staging-guestbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10