apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development-ingress-nginx
  namespace: argo-system
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: development

  source:
    repoURL: https://github.com/blackjokie/k8s-manifest
    targetRevision: HEAD
    path: charts/development-ingress-nginx/
    directory:
      recurse: true  # penting: ini agar semua subfolder dibaca
    helm:
      releaseName: ingress-nginx
      valuesFile:
        - ../../../releases/development/development-ingress-nginx/releases.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: development-ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10